development:
  adapter: postgresql
  encoding: unicode
  database: lefty_development
  pool: 5
  username: mashype
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lefty_test
  pool: 5
  username: mashype
  password:

production:
  database: <%= ENV["DATABASE_NAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  adapter: postgresql
  host: ec2-107-20-174-127.compute-1.amazonaws.com
